### ISSUE TITLE
Request for TransRadar Model Source Code and Configuration Details

### ISSUE THREAD

**Issue by ybktrice** [YahiDar/TransRadar#2]
Hello,

This is an excellent piece of research. Could you please provide the implementation of the TransRadar model on the RADIal dataset? Additionally, the paper does not mention the details of the model architecture and configuration.

Thank you very much for considering my request. I look forward to your response.

**Comment by YahiDar** [comment]
Hi,
Thank you for your comment.
Sadly we do not have the Radial implementation, however, it uses the repository in that paper but with the middle backbone replaced by our proposed transformer implementation. You can just call the library and plug it in there easily.

**Comment by ybktrice** [comment]
> Hi, Thank you for your comment. Sadly we do not have the Radial implementation, however, it uses the repository in that paper but with the middle backbone replaced by our proposed transformer implementation. You can just call the library and plug it in there easily.

Hello,
Thank you for your response.  I will follow your suggestion!
